Repository obviyus/SuperSeriousBot, pull requests merged in 2021-12, with the labels that each got.

#211 [api] add support for default weather location
  api/__init__.py
  api/dice.py
  api/setw.py
  api/weather.py
  main.py
Labels: enhancement

#215 [log] add logging
  .github/workflows/publish-image.yml
  Dockerfile
  api/album.py
  api/audio.py
  configuration/.env.example
  configuration/__init__.py
  dev/botstats.py
  main.py
Labels: enhancement

#216 Refactor a few functions for v1.0.0
  .github/workflows/publish-image.yml
  .github/workflows/python.yml
  .pre-commit-config.yaml
  VERSION
  api/__init__.py
  api/animals.py
  api/calc.py
  api/covid.py
  api/csgo.py
  api/define.py
  api/gif.py
  api/goodreads.py
  api/insult.py
  api/joke.py
  api/pfp.py
  api/pic.py
  api/seinfeld.py
  api/steamstats.py
  api/weather.py
  files/seinfeld_song.mp3
  links/__init__.py
  links/link_handler.py
  links/reddit.py
  links/youtube.py
  main.py
  pydub_patch.py
  setup.cfg
Labels: bug, enhancement

#217 [links] remove unused link handlers
  VERSION
  main.py
Labels: bug

#218 Refactor logging and commands dict
  api/pic.py
  api/search.py
  configuration/.env.example
  configuration/__init__.py
  main.py
Labels: enhancement

#222 [pydub] Patch to remove redundant `pydub_patch.py`
  Dockerfile
  VERSION
  pydub_patch.py
  requirements.txt
Labels: bug

#223 Add /meme, /randdit and /person commands
  api/__init__.py
  api/meme.py
  api/person.py
  api/pic.py
  api/randdit.py
  main.py
Labels: enhancement

#224 [randdit] fix code 429
  VERSION
  api/randdit.py
Labels: bug

#225 Add praw to /randdit
  api/randdit.py
  configuration/__init__.py
  main.py
  requirements.txt
Labels: bug, enhancement

#228 Refactor /dl using yt-dlp
  VERSION
  links/dl.py
  requirements.txt
Labels: bug
