Repository obviyus/SuperSeriousBot, pull requests merged in 2022-01, with the labels that each got.

#241 Add auto generated release notes and black linting to ci
  .github/release.yml
  .github/workflows/codesee-arch-diagram.yml
  .github/workflows/python.yml
  .github/workflows/semgrep.yml
  api/album.py
  api/animals.py
  api/audio.py
  api/covid.py
  api/define.py
  api/dice.py
  api/gif.py
  api/goodreads.py
  api/hltb.py
  api/insult.py
  api/joke.py
  api/pfp.py
  api/response.py
  api/search.py
  api/sed.py
  api/spurdo.py
  api/steamstats.py
  api/tldr.py
  api/translate.py
  api/tts.py
  api/ud.py
  api/uwu.py
  api/vision.py
  api/wait.py
  api/weather.py
  api/wmark.py
  chat_management/ban.py
  chat_management/kick.py
  chat_management/seen.py
  chat_management/stats.py
  configuration/__init__.py
  dev/__init__.py
  dev/groups.py
  dev/users.py
  links/dl.py
  main.py
  requirements.txt
Labels: ci, dev enhancement

#242 Publish new image only with new github release
  .github/workflows/publish-image.yml
  VERSION
Labels: ci, dev enhancement

#244 Add typing chat action to all commands
  .github/workflows/publish-image.yml
  main.py
  requirements.txt
Labels: enhancement

#245 [links] add comments to links
  links/__init__.py
  links/reddit_comment.py
  main.py
Labels: enhancement, new command

#246 [randdit] Fix default parameters and change invocation to /r
  api/__init__.py
  api/randdit.py
  main.py
Labels: bug
